cluster_number_density – fortperc
cluster_number_density Subroutine
39 statements
Source File
public subroutine cluster_number_density(p, L, num_samples, bin_mids, results, binsize_base)
Calculate the number density of clusters with different sizes. The cluster number density is defined as \begin{equation} n(s,p) = \sum_{\text{MC-samples}} \frac{\text{number of clusters with size }s} {L^2\cdot\text{number of MC-samples}}. \end{equation} Direct calculations will usually give bad results, as there will be very few clusters with large sizes compared to the numbers of clusters with small sizes. This is circumvented by doing logarithmic binning and averaging, i.e. \begin{equation} n\left([s+\Delta s),p\right) = \sum_{\text{MC-samples}} \frac{\text{number of clusters with size }s \in[s,s+\Delta s)} {\Delta s\cdot L^2\cdot\text{number of MC-samples}}, \label{eq:nsp} \end{equation} where \(\Delta s\) are logarithmically distributed. After execution, bin_mids will contain the centres of the bins.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
Probability for a given site to allow transport.
integer, intent(in) :: L
Percolating systems will be \(L\times L\).
integer, intent(in) :: num_samples
Results will be averaged over this number of Monte Carlo-samples. Sampling is parallelised.
real(kind=dp), intent(inout), dimension(:), allocatable :: bin_mids
Centres of bins.
real(kind=dp), intent(inout), dimension(:), allocatable :: results
Cluster number density in \eqref{eq:nsp}.
real(kind=dp), intent(in), optional :: binsize_base
The edges of the logarithmically distributed bins will be integer powers of this number. Default: 1.5.
Calls
All Procedures
cluster_number_density create_binary_matrix find_intersection find_sizes find_spanning_cluster growcluster hoshen_kopelman label label_stackoverflow linfit linspace spanning_density spanning_probability spanning_probability_inverse stringfromint uf_find uf_union
Call graph
cluster_number_density calls find_sizes, create_binary_matrix, label, find_spanning_cluster
label calls hoshen_kopelman
find_spanning_cluster calls find_intersection
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find