create_binary_matrix – fortperc
create_binary_matrix Function
10 statements
Source File
public function create_binary_matrix(p, L) result(binary_matrix)
C
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
integer, intent(in) :: L
Return Value logical, dimension(:,:),allocatable
Called By
All Procedures
cluster_number_density create_binary_matrix find_intersection find_sizes find_spanning_cluster growcluster has_spanning_cluster_one_sample hoshen_kopelman label label_stackoverflow linfit linspace spanning_density spanning_density_one_sample spanning_probability spanning_probability_inverse stringfromint uf_find uf_union
Call graph
has_spanning_cluster_one_sample calls create_binary_matrix
spanning_density_one_sample calls create_binary_matrix
cluster_number_density calls create_binary_matrix
spanning_probability calls has_spanning_cluster_one_sample
spanning_probability_inverse calls spanning_probability
spanning_density calls spanning_density_one_sample