hoshen_kopelman – fortperc
hoshen_kopelman Function
51 statements
Source File
public function hoshen_kopelman(matrix) result(num_clusters)
Hoshen-Kopelman algorithm for labelling clusters on a binary matrix.
The function takes in a binary matrix (zeros and positive numbers), labels the clusters of positive numbers and returns the total number of clusters found. The argument matrix is overwritten with the labels.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:,:) :: matrix
The matrix to be labelled.
Return Value integer
The total number of disjoint clusters labelled.
Calls
Called By
All Procedures
cluster_number_density create_binary_matrix find_intersection find_sizes find_spanning_cluster growcluster has_spanning_cluster_one_sample hoshen_kopelman label label_stackoverflow linfit linspace spanning_density spanning_density_one_sample spanning_probability spanning_probability_inverse stringfromint uf_find uf_union
Call graph
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find
label calls hoshen_kopelman
has_spanning_cluster_one_sample calls label
spanning_density_one_sample calls label
cluster_number_density calls label
spanning_probability calls has_spanning_cluster_one_sample
spanning_probability_inverse calls spanning_probability
spanning_density calls spanning_density_one_sample