spanning_probability_inverse – fortperc
spanning_probability_inverse Function
22 statements
Source File
public function spanning_probability_inverse(x, L, num_samples, tolerance) result(p_x)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
integer, intent(in) :: L
integer, intent(in) :: num_samples
real(kind=dp), intent(in) :: tolerance
Return Value real(kind=dp)
Calls
All Procedures
cluster_number_density create_binary_matrix find_intersection find_sizes find_spanning_cluster growcluster has_spanning_cluster_one_sample hoshen_kopelman label label_stackoverflow linfit linspace spanning_density spanning_density_one_sample spanning_probability spanning_probability_inverse stringfromint uf_find uf_union
Call graph
spanning_probability_inverse calls spanning_probability
spanning_probability calls has_spanning_cluster_one_sample
has_spanning_cluster_one_sample calls label, create_binary_matrix, find_spanning_cluster
label calls hoshen_kopelman
find_spanning_cluster calls find_intersection
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find