uf_find – fortperc
uf_find Function
15 statements
Source File
public function uf_find(x, labels) result(y)
Union-Find find algorithm: Find the lowest corresponding label. Relabelling is done when necessary.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: x
integer, intent(inout), dimension(:) :: labels
Return Value integer
Called By
All Procedures
cluster_number_density create_binary_matrix find_intersection find_sizes find_spanning_cluster growcluster has_spanning_cluster_one_sample hoshen_kopelman label label_stackoverflow linfit linspace spanning_density spanning_density_one_sample spanning_probability spanning_probability_inverse stringfromint uf_find uf_union
Call graph
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find
label calls hoshen_kopelman
has_spanning_cluster_one_sample calls label
spanning_density_one_sample calls label
cluster_number_density calls label
spanning_probability calls has_spanning_cluster_one_sample
spanning_probability_inverse calls spanning_probability
spanning_density calls spanning_density_one_sample