find_spanning_cluster – fortperc
find_spanning_cluster Function
11 statements
Source File
public function find_spanning_cluster(labelled_matrix, num_labels) result(spanning_label)
Find the label of the percolating cluster, i.e. the one spanning from one side of the system to the opposing side.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:) :: labelled_matrix
Labelled matrix of clusters from hoshen_kopelman/label.
integer, intent(in) :: num_labels
Known number of clusters.
Return Value integer
Label of the percolating cluster. -1 if no percolating cluster is found.
Calls
Called by
Contents
None
Call graph
find_spanning_cluster calls find_intersection
probability_distribution calls find_spanning_cluster
random_walkers calls find_spanning_cluster
cluster_number_density calls find_spanning_cluster