probability_distribution – fortperc
probability_distribution Function
54 statements
Source File
public function probability_distribution(p, L, num_steps, num_walkers, num_systems, num_hists) result(result_hist)
Start num_walkers on the percolating cluster of each of num_systems systems, and compute num_hists histograms of the distribution of particles.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
The probability for each site to allow transport.
integer, intent(in) :: L
The system size.
integer, intent(in) :: num_steps
The number of steps which the random walkers take.
integer, intent(in) :: num_walkers
The number of random walkers for each system over which to average.
integer, intent(in) :: num_systems
The number of systems over which to average.
integer, intent(in) :: num_hists
The number of histograms to be returned.
Return Value real(kind=dp), dimension(:,:),allocatable
Array of histograms. The first row contains the centres of the bins, while the remaining num_hists+1 rows each contain one histogram.
Calls
Contents
None
Call graph
probability_distribution calls mark_percolating_with_periodic, label, create_binary_matrix, find_spanning_cluster, one_random_walker
label calls hoshen_kopelman
find_spanning_cluster calls find_intersection
one_random_walker calls find_random_point, periodic_wraparound
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find