random_walkers – fortperc
random_walkers Function
30 statements
Source File
public function random_walkers(p, L, num_systems, num_walkers, num_steps) result(displacement)
Start num_walkers on the percolating cluster of each of num_systems systems, and return the averaged displacement.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: p
The probability for each site to allow transport.
integer, intent(in) :: L
The system size.
integer, intent(in) :: num_systems
The number of systems over which to average.
integer, intent(in) :: num_walkers
The number of random walkers for each system over which to average.
integer, intent(in) :: num_steps
The number of steps which the random walkers take.
Return Value real(kind=dp), dimension(:),allocatable
Array of squared displacements, which has dimension (num_steps + 1), and should logically have dimension(0:num_steps), such that the i'th element contains the displacement after i steps. Averaged over all systems and all walkers.
Calls
Contents
None
Call graph
random_walkers calls mark_percolating_with_periodic, label, create_binary_matrix, find_spanning_cluster, one_random_walker
label calls hoshen_kopelman
find_spanning_cluster calls find_intersection
one_random_walker calls find_random_point, periodic_wraparound
hoshen_kopelman calls uf_find, uf_union
uf_union calls uf_find