uf_union – fortperc
uf_union Function
7 statements
Source File
public function uf_union(x, y, labels) result(canonical_label)
Union-Find union algorithm: Merge two labels, return the result.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: x
Labels to merge.
integer, intent(in) :: y
Labels to merge.
integer, intent(inout), dimension(:) :: labels
List of labels.
Return Value integer
Calls
Called by
Contents
None
Call graph
uf_union calls uf_find
hoshen_kopelman calls uf_union
label calls hoshen_kopelman
probability_distribution calls label
random_walkers calls label
cluster_number_density calls label